import {
  LayoutDashboard,
  Users,
  Shield,
  HeartPulse,
  Baby,
  Stethoscope,
  Milk,
  Activity,
  BookOpen,
  GraduationCap,
  User,
  UserCheck,
  Syringe,
  CalendarClock,
  Map,
  MapPin,
  Landmark,
  MapPinned,
  Home,
  Hospital,
} from "lucide-react";

export const navIcons: Record<string, React.ElementType> = {
  Inicio: LayoutDashboard,
  Usuarios: Users,
  Roles: Shield,
  Pregestantes: HeartPulse,
  Gestantes: Baby,
  Posgestantes: Stethoscope,
  Lactantes: Milk,
  Transicional: Activity,
  Preescolar: BookOpen,
  Escolar: GraduationCap,
  Adolescentes: User,
  Adultos: UserCheck,
  "Ficha de Vacunacion": Syringe,
  "Gestion de Guardias": CalendarClock,
  Provincias: Map,
  Municipios: MapPin,
  "Consejos Populares": Landmark,
  Circunscripciones: MapPinned,
  CDR: Home,
  Policlinicos: Hospital,
  Consultorios: Stethoscope,
};
